name: GitHub Pages

on:                                              
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1                  
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.136.2'
        extended: true

    - name: Build                                
      run: hugo --minify

    - name: Deploy                               
      uses: peaceiris/actions-gh-pages@v4
      with:
        cname: codingarret.dev
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: gh-pages